# The URL the site will be built for
base_url = "https://zapb.vercel.app"

title = "Zap's website"
author = "Zap"
description = "Bui Huy Giap's personal website and blog"

compile_sass = false
build_search_index = false

generate_feed = true
feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "one-dark"
smart_punctuation = true

[extra]
# Put all your custom variables here
