[projects.repalette]
name        = "Repalette"
description = """
A website and command line utility that allows you to theme an image to a
certain color palette.
"""
recent      = true

[projects.uttt]
name        = "Ultimate tic-tac-toe"
description = """
A browser-based Ultimate tic-tac-toe game with a powerful Monte Carlo tree
search AI adversary."""
recent      = true

[projects.2048-ai]
name        = "2048 AI"
description = """
A very efficient expectimax 2048 AI algorithm.
"""
recent      = true

[projects.tetris]
name        = "Tetris clone"
description = """
Simple Tetris implementation in C and OpenGL.
"""
